---
abstract: 'Curses Client for Stackato'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Stackato::Stackrad
name: Stackato-Stackrad
no_index:
  directory:
    - inc
    - t
requires:
  Curses::UI: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  URI::Escape: 0
  YAML::XS: 0
resources:
  homepage: https://github.com/ingydotnet/stackrad/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/stackrad.git
    web: https://github.com/ingydotnet/stackrad/tree
version: 0.02
