---
abstract: 'Curses Client for Stackato'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Stackato-Stackrad
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Curses::UI: '0'
  HTTP::Request: '0'
  JSON::XS: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  Mo: '0'
  URI::Escape: '0'
  YAML::XS: '0'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/stackato-stackrad-pm/issues
  homepage: https://github.com/ingydotnet/stackato-stackrad-pm
  repository: https://github.com/ingydotnet/stackato-stackrad-pm.git
version: '0.09'
